//! Skill synchronization for CLI agents.
//!
//! CLI agents (Cursor, Claude Code, Codex, Antigravity, Kiro, Copilot) are external
//! subprocesses — we cannot control their system prompts. Each agent has its own
//! native rules system that automatically loads project-level instruction files:
//!
//! | Agent       | Rules file                              |
//! |-------------|-----------------------------------------|
//! | Cursor CLI  | `.cursor/rules/*.mdc` (alwaysApply)     |
//! | Claude Code | `.claude/rules/*.md`                    |
//! | Codex       | `AGENTS.md` (walks up from cwd)         |
//! | Copilot     | reads `CLAUDE.md`, `AGENTS.md`, etc.    |
//! | Kiro        | no known rules file                     |
//!
//! This module writes orgii-managed skill files into each agent's native rules
//! location before the CLI subprocess is spawned, then cleans them up after
//! the session completes.

use std::fs;
use std::path::{Path, PathBuf};

use agent_core::skills::loader::{global_skills_dir, SkillInfo, SkillsLoader};
use key_vault::key_store::ModelType;

/// Marker header embedded in every generated file so we can identify our own files.
const ORGII_MARKER: &str = "<!-- generated by orgii — do not edit manually -->";
const PROVIDER_SKILL_CATALOG_CHAR_BUDGET: usize = 8_000;
const PROVIDER_SKILL_DESCRIPTION_MAX_CHARS: usize = 250;

/// Sync skills into the CLI agent's native rules files.
///
/// Returns the list of file paths that were written, for cleanup after the
/// session completes. Files are named with a `orgii-` prefix to avoid
/// colliding with user-owned rule files.
///
/// If `skills_enabled` is false or no skills are found, no files are written.
pub fn sync_skills_for_agent(
    agent: &ModelType,
    workspace_path: &Path,
    skills_enabled: bool,
    disabled_skills: &[String],
) -> Vec<PathBuf> {
    if !skills_enabled {
        return Vec::new();
    }

    let loader = SkillsLoader::new(&workspace_path.join(".orgii"))
        .with_builtin_dir(global_skills_dir())
        .with_disabled_skills(disabled_skills.to_vec());

    let all_skills: Vec<SkillInfo> = loader
        .list_skills()
        .into_iter()
        .filter(|skill| skill.enabled && skill.available)
        .collect();

    if all_skills.is_empty() {
        return Vec::new();
    }

    let content = build_skills_content(&all_skills);

    let targets = rule_targets_for_agent(agent, workspace_path);
    let mut written: Vec<PathBuf> = Vec::new();

    for target in targets {
        match write_rule_file(&target, &content) {
            Ok(()) => {
                tracing::info!(
                    "[skill_sync] Wrote {} skill(s) to {}",
                    all_skills.len(),
                    target.display()
                );
                written.push(target);
            }
            Err(err) => {
                tracing::warn!("[skill_sync] Failed to write {}: {}", target.display(), err);
            }
        }
    }

    written
}

/// Remove files that were created by `sync_skills_for_agent`.
pub fn cleanup_synced_skill_files(paths: &[PathBuf]) {
    for path in paths {
        if !path.exists() {
            continue;
        }
        // Safety check: only delete files containing our marker
        if !is_orgii_managed_file(path) {
            tracing::warn!(
                "[skill_sync] Skipping cleanup of {} — missing orgii marker",
                path.display()
            );
            continue;
        }
        if let Err(err) = fs::remove_file(path) {
            tracing::warn!(
                "[skill_sync] Failed to clean up {}: {}",
                path.display(),
                err
            );
        }
    }
}

fn is_orgii_managed_file(path: &Path) -> bool {
    fs::read_to_string(path)
        .map(|content| content.contains(ORGII_MARKER))
        .unwrap_or(false)
}

/// Determine the rule file path(s) to write for a given agent.
fn rule_targets_for_agent(agent: &ModelType, workspace_path: &Path) -> Vec<PathBuf> {
    match agent {
        ModelType::CursorCli => {
            vec![workspace_path
                .join(".cursor")
                .join("rules")
                .join("orgii-skills.mdc")]
        }
        ModelType::ClaudeCode => {
            vec![workspace_path
                .join(".claude")
                .join("rules")
                .join("orgii-skills.md")]
        }
        // Codex does not discover arbitrary markdown below `.codex/`.
        // Mutating a user's root AGENTS.md would race concurrent sessions, so
        // its guaranteed delivery path is the provider-neutral prompt fallback.
        ModelType::Codex => Vec::new(),
        ModelType::Copilot => {
            // Copilot reads CLAUDE.md, AGENTS.md, and GEMINI.md.
            // Write to .github/instructions/ which Copilot explicitly supports.
            vec![workspace_path
                .join(".github")
                .join("instructions")
                .join("orgii-skills.instructions.md")]
        }
        ModelType::Kiro => {
            // Kiro has no known rules file system — skills are injected into
            // the user prompt instead (handled separately in runner.rs).
            Vec::new()
        }
        // API key providers are not CLI agents
        _ => Vec::new(),
    }
}

/// Build the provider-neutral progressive skill catalog.
///
/// Returns `None` if skills are disabled or no skills found.
pub fn build_skills_prompt_injection(
    workspace_path: &Path,
    skills_enabled: bool,
    disabled_skills: &[String],
) -> Option<String> {
    if !skills_enabled {
        return None;
    }

    let loader = SkillsLoader::new(&workspace_path.join(".orgii"))
        .with_builtin_dir(global_skills_dir())
        .with_disabled_skills(disabled_skills.to_vec());

    let all_skills: Vec<SkillInfo> = loader
        .list_skills()
        .into_iter()
        .filter(|skill| skill.enabled && skill.available)
        .collect();

    if all_skills.is_empty() {
        return None;
    }

    let content = build_skills_content(&all_skills);
    Some(format!("<skills>\n{}\n</skills>", content))
}

/// Build the provider-neutral context envelope used by every CLI. The
/// workspace instruction section is shared with the Rust harness; the skill
/// catalog stays progressive-disclosure only (descriptions + paths, never
/// every SKILL.md body).
pub fn build_cli_context_prompt_injection(
    workspace_path: &Path,
    skills_enabled: bool,
    disabled_skills: &[String],
) -> Option<String> {
    let mut sections = Vec::new();
    if let Some(instructions) =
        agent_core::session::prompt::load_workspace_instructions(workspace_path)
    {
        if !instructions.trim().is_empty() {
            sections.push(format!("## Workspace Instructions\n\n{instructions}"));
        }
    }
    if let Some(skills) =
        build_skills_prompt_injection(workspace_path, skills_enabled, disabled_skills)
    {
        sections.push(skills);
    }
    if sections.is_empty() {
        None
    } else {
        Some(format!(
            "<orgii_provider_context>\n{}\n</orgii_provider_context>",
            sections.join("\n\n---\n\n")
        ))
    }
}

// ==========================================================================
// Private helpers
// ==========================================================================

/// Build the formatted skills content shared by all agents.
fn build_skills_content(skills: &[SkillInfo]) -> String {
    let mut skills = skills.iter().collect::<Vec<_>>();
    skills.sort_by(|left, right| {
        left.name
            .cmp(&right.name)
            .then_with(|| left.path.cmp(&right.path))
    });

    // Keep discovery byte-stable and bounded. Full SKILL.md bodies are loaded
    // only after the provider selects a matching entry.
    let mut description_budget = PROVIDER_SKILL_DESCRIPTION_MAX_CHARS;
    let render_lines = |description_budget: usize| -> Vec<String> {
        skills
            .iter()
            .map(|skill| {
                let desc = if skill.description.is_empty() {
                    "No description".to_string()
                } else {
                    agent_core::utils::safe_truncate_chars_to_string(
                        &skill.description,
                        description_budget,
                    )
                };
                format!(
                    "- **{}** ({}): {}\n  Path: `{}`",
                    skill.name,
                    skill.source,
                    desc,
                    skill.path.display()
                )
            })
            .collect()
    };
    let mut summary_lines = render_lines(description_budget);
    let mut rendered_chars = summary_lines
        .iter()
        .map(|line| line.chars().count())
        .sum::<usize>();
    if rendered_chars > PROVIDER_SKILL_CATALOG_CHAR_BUDGET && !skills.is_empty() {
        let overflow = rendered_chars - PROVIDER_SKILL_CATALOG_CHAR_BUDGET;
        description_budget = description_budget
            .saturating_sub(overflow.div_ceil(skills.len()))
            .max(20);
        summary_lines = render_lines(description_budget);
        rendered_chars = summary_lines
            .iter()
            .map(|line| line.chars().count())
            .sum::<usize>();
    }
    if rendered_chars > PROVIDER_SKILL_CATALOG_CHAR_BUDGET {
        summary_lines = skills
            .iter()
            .map(|skill| format!("- **{}** — `{}`", skill.name, skill.path.display()))
            .collect();
    }

    format!(
        "## Skills (mandatory)\n\n\
         Before replying: scan the skill descriptions below.\n\
         - If exactly one skill clearly applies: read its SKILL.md using read_file, then follow it.\n\
         - If multiple could apply: choose the most specific one, then read/follow it.\n\
         - If none clearly apply: do not read any SKILL.md.\n\
         Constraints: never read more than one skill up front; only read after selecting.\n\n\
         {}",
        summary_lines.join("\n")
    )
}

/// Write a rule file with the appropriate wrapper for its format.
fn write_rule_file(target: &Path, content: &str) -> Result<(), String> {
    // Ensure parent directory exists
    if let Some(parent) = target.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent).map_err(|err| {
                format!("Failed to create directory {}: {}", parent.display(), err)
            })?;
        }
    }

    let ext = target.extension().and_then(|e| e.to_str()).unwrap_or("");
    let wrapped = match ext {
        "mdc" => format_mdc(content),
        _ => format_markdown(content),
    };

    fs::write(target, wrapped)
        .map_err(|err| format!("Failed to write {}: {}", target.display(), err))
}

/// Wrap content as a Cursor `.mdc` file with `alwaysApply: true` frontmatter.
fn format_mdc(content: &str) -> String {
    format!(
        "---\ndescription: Skills injected by orgii for coding sessions\nalwaysApply: true\n---\n\n{marker}\n\n{content}",
        marker = ORGII_MARKER,
        content = content,
    )
}

/// Wrap content as a plain markdown file with the orgii marker.
fn format_markdown(content: &str) -> String {
    format!(
        "{marker}\n\n{content}",
        marker = ORGII_MARKER,
        content = content,
    )
}

// ==========================================================================
// Convention sync (replaces sync_conventions_to_cursorrules)
// ==========================================================================

/// Sync project conventions (`.orgii/agent-rules.md`) to each CLI agent's
/// native rules file.
///
/// Replaces the old `sync_conventions_to_cursorrules()` which wrote to the
/// deprecated `.cursorrules` file (which Cursor agent mode ignores).
pub fn sync_conventions_for_agent(agent: &ModelType, workspace_path: &Path) -> Vec<PathBuf> {
    let targets = convention_targets_for_agent(agent, workspace_path);
    let conventions_path = workspace_path.join(".orgii").join("agent-rules.md");
    let content = match fs::read_to_string(&conventions_path) {
        Ok(content) => {
            agent_core::session::prompt::strip_retired_workspace_instruction_blocks(&content)
        }
        Err(_) => String::new(),
    };

    // A missing/empty source must also remove an older ORGII-managed copy.
    // Otherwise uninstalling the source leaves the provider's native rules
    // active until some unrelated cleanup happens to find them.
    if content.trim().is_empty() {
        let stale_managed_targets = targets
            .into_iter()
            .filter(|target| is_orgii_managed_file(target))
            .collect::<Vec<_>>();
        cleanup_synced_skill_files(&stale_managed_targets);
        return Vec::new();
    }

    let mut written: Vec<PathBuf> = Vec::new();

    for target in targets {
        // Skip if a non-orgii file already exists at this path
        if target.exists() && !is_orgii_managed_file(&target) {
            continue;
        }

        match write_rule_file(&target, &content) {
            Ok(()) => {
                tracing::info!("[skill_sync] Synced conventions to {}", target.display());
                written.push(target);
            }
            Err(err) => {
                tracing::warn!(
                    "[skill_sync] Failed to sync conventions to {}: {}",
                    target.display(),
                    err
                );
            }
        }
    }

    written
}

/// Determine convention file paths for each agent type.
fn convention_targets_for_agent(agent: &ModelType, workspace_path: &Path) -> Vec<PathBuf> {
    match agent {
        ModelType::CursorCli => {
            vec![workspace_path
                .join(".cursor")
                .join("rules")
                .join("orgii-conventions.mdc")]
        }
        ModelType::ClaudeCode => {
            vec![workspace_path
                .join(".claude")
                .join("rules")
                .join("orgii-conventions.md")]
        }
        ModelType::Codex => Vec::new(),
        ModelType::Copilot => {
            vec![workspace_path
                .join(".github")
                .join("instructions")
                .join("orgii-conventions.instructions.md")]
        }
        ModelType::Kiro => Vec::new(),
        _ => Vec::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::{build_skills_prompt_injection, sync_conventions_for_agent, ORGII_MARKER};
    use key_vault::key_store::ModelType;

    const RETIRED_BLOCK: &str = "<!-- brick:managed:start v=9 -->\nRun `brick explain src/main.rs:1` first.\n<!-- brick:managed:end -->";

    #[test]
    fn provider_skill_catalog_is_stable_bounded_and_keeps_load_paths() {
        let workspace = tempfile::tempdir().expect("workspace");
        for index in 0..80 {
            let skill_dir = workspace
                .path()
                .join(".agents/skills")
                .join(format!("skill-{index:03}"));
            std::fs::create_dir_all(&skill_dir).expect("create skill dir");
            std::fs::write(
                skill_dir.join("SKILL.md"),
                format!(
                    "---\nname: skill-{index:03}\ndescription: {}\n---\n\nBody {index}",
                    "description ".repeat(80)
                ),
            )
            .expect("write skill");
        }

        let first = build_skills_prompt_injection(workspace.path(), true, &[])
            .expect("provider skill catalog");
        let second = build_skills_prompt_injection(workspace.path(), true, &[])
            .expect("provider skill catalog");
        assert_eq!(
            first, second,
            "catalog must be byte-stable for digest reuse"
        );
        assert!(first.contains("skill-000"));
        assert!(first.contains("SKILL.md"));
        assert!(
            first.chars().count() <= 12_000,
            "catalog must stay near its 8k entry budget: {} chars",
            first.chars().count()
        );
    }

    #[test]
    fn convention_sync_filters_retired_managed_blocks() {
        let workspace = tempfile::tempdir().expect("workspace");
        let orgii = workspace.path().join(".orgii");
        std::fs::create_dir_all(&orgii).expect("create .orgii");
        std::fs::write(
            orgii.join("agent-rules.md"),
            format!("{RETIRED_BLOCK}\n\nKeep this rule."),
        )
        .expect("write conventions");

        let written = sync_conventions_for_agent(&ModelType::CursorCli, workspace.path());
        assert_eq!(written.len(), 1);
        let content = std::fs::read_to_string(&written[0]).expect("read synced rules");
        assert!(content.contains("Keep this rule."));
        assert!(!content.contains("brick explain"));
        assert!(!content.contains("brick:managed"));
    }

    #[test]
    fn retired_only_source_removes_stale_orgii_managed_copy() {
        let workspace = tempfile::tempdir().expect("workspace");
        let orgii = workspace.path().join(".orgii");
        let target = workspace.path().join(".cursor/rules/orgii-conventions.mdc");
        std::fs::create_dir_all(&orgii).expect("create .orgii");
        std::fs::create_dir_all(target.parent().expect("target parent"))
            .expect("create target parent");
        std::fs::write(orgii.join("agent-rules.md"), RETIRED_BLOCK).expect("write conventions");
        std::fs::write(&target, format!("{ORGII_MARKER}\n\nOld generated rules."))
            .expect("write stale target");

        let written = sync_conventions_for_agent(&ModelType::CursorCli, workspace.path());
        assert!(written.is_empty());
        assert!(!target.exists());
    }

    #[test]
    fn empty_source_preserves_user_owned_native_rules_file() {
        let workspace = tempfile::tempdir().expect("workspace");
        let target = workspace.path().join(".cursor/rules/orgii-conventions.mdc");
        std::fs::create_dir_all(target.parent().expect("target parent"))
            .expect("create target parent");
        std::fs::write(&target, "User-owned rule.").expect("write user target");

        let written = sync_conventions_for_agent(&ModelType::CursorCli, workspace.path());
        assert!(written.is_empty());
        assert_eq!(
            std::fs::read_to_string(target).expect("read user target"),
            "User-owned rule."
        );
    }
}
