/**
 * Codex app skins.
 *
 * Seeds are extracted from the Codex desktop app's bundled theme registry and
 * reduced with Codex's own rules: `surface` and `ink` come from the first
 * present `editor.background` / `editor.foreground` (falling back through the
 * sideBar and panel keys), `accent` from the first sufficiently chromatic
 * `activityBarBadge.background` / `textLink.foreground` /
 * `editorCursor.foreground`, and the semantic hues from the matching
 * `gitDecoration.*` and `terminal.ansi*` entries. Partner themes (Linear,
 * Notion, Vercel, Raycast, Sentry, Xcode) ship an explicit `chromeTheme` seed,
 * which overrides the derived values verbatim.
 *
 * Syntax colors are the canonical scope for each category, preferring an exact
 * TextMate scope over a longer descendant of it.
 *
 * DO NOT EDIT BY HAND. Regenerate with the scripts in `scripts/appearance/`.
 */
import type { SkinDefinition } from "./types";

export const CODEX_SKINS: readonly SkinDefinition[] = [
  {
    id: "codex-ayu",
    label: "Ayu",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#10141c",
          ink: "#bfbdb6",
          accent: "#e6b450",
          contrast: 60,
          semanticColors: {
            diffAdded: "#70bf56",
            diffRemoved: "#f26d78",
            skill: "#d0a1ff",
          },
          syntax: {
            comment: "#5a6673",
            string: "#aad94c",
            keyword: "#ff8f40",
            function: "#ffb454",
            variable: "#bfbdb6",
            number: "#d2a6ff",
            operator: "#f29668",
            tag: "#39bae6",
            attribute: "#ffb454",
            property: "#39bae6",
            type: "#39bae6",
            constant: "#d2a6ff",
            invalid: "#d95757",
          },
        },
        sourceName: "ayu-dark",
      },
    },
  },
  {
    id: "codex-catppuccin",
    label: "Catppuccin",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#eff1f5",
          ink: "#4c4f69",
          accent: "#8839ef",
          contrast: 45,
          semanticColors: {
            diffAdded: "#40a02b",
            diffRemoved: "#d20f39",
            skill: "#8839ef",
          },
          syntax: {
            comment: "#7c7f93",
            string: "#40a02b",
            keyword: "#8839ef",
            function: "#1e66f5",
            variable: "#e64553",
            number: "#fe640b",
            operator: "#179299",
            tag: "#1e66f5",
            attribute: "#df8e1d",
            property: "#1e66f5",
            type: "#df8e1d",
            constant: "#d20f39",
          },
        },
        sourceName: "catppuccin-latte",
      },
      dark: {
        seed: {
          surface: "#1e1e2e",
          ink: "#cdd6f4",
          accent: "#cba6f7",
          contrast: 60,
          semanticColors: {
            diffAdded: "#a6e3a1",
            diffRemoved: "#f38ba8",
            skill: "#cba6f7",
          },
          syntax: {
            comment: "#9399b2",
            string: "#a6e3a1",
            keyword: "#cba6f7",
            function: "#89b4fa",
            variable: "#eba0ac",
            number: "#fab387",
            operator: "#94e2d5",
            tag: "#89b4fa",
            attribute: "#f9e2af",
            property: "#89b4fa",
            type: "#f9e2af",
            constant: "#f38ba8",
          },
        },
        sourceName: "catppuccin-mocha",
      },
    },
  },
  {
    id: "codex-absolutely",
    label: "Absolutely",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#f9f9f7",
          ink: "#2d2d2b",
          accent: "#cc7d5e",
          contrast: 45,
          semanticColors: {
            diffAdded: "#00a240",
            diffRemoved: "#ba2623",
            skill: "#cc7d5e",
          },
          syntax: {
            comment: "#939391",
            string: "#00c853",
            keyword: "#ff5f38",
            function: "#2d2d2b",
            variable: "#2d2d2b",
            number: "#ff5f38",
            operator: "#ff5f38",
            property: "#bc7559",
            type: "#bc7559",
            constant: "#ff5f38",
          },
        },
        sourceName: "Absolutely Light",
      },
      dark: {
        seed: {
          surface: "#2d2d2b",
          ink: "#f9f9f7",
          accent: "#cc7d5e",
          contrast: 60,
          semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#fa423e",
            skill: "#cc7d5e",
          },
          syntax: {
            comment: "#b2b2b0",
            string: "#00c853",
            keyword: "#ff5f38",
            function: "#f9f9f7",
            variable: "#f9f9f7",
            number: "#ff5f38",
            operator: "#ff5f38",
            property: "#d28e73",
            type: "#d28e73",
            constant: "#ff5f38",
          },
        },
        sourceName: "Absolutely Dark",
      },
    },
  },
  {
    id: "codex-codex",
    label: "Codex",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#ffffff",
          ink: "#0d0d0d",
          accent: "#0169cc",
          contrast: 45,
          semanticColors: {
            diffAdded: "#00a240",
            diffRemoved: "#e02e2a",
            skill: "#751ed9",
          },
          syntax: {
            comment: "#666666",
            string: "#008809",
            keyword: "#d53538",
            function: "#751ed9",
            variable: "#bd5800",
            number: "#0071ea",
            operator: "#666666",
            tag: "#d53538",
            attribute: "#0071ea",
            property: "#666666",
            type: "#751ed9",
            constant: "#0071ea",
            invalid: "#ffffff",
          },
        },
        sourceName: "Codex Light",
      },
      dark: {
        seed: {
          surface: "#111111",
          ink: "#fcfcfc",
          accent: "#0169cc",
          contrast: 60,
          semanticColors: {
            diffAdded: "#00a240",
            diffRemoved: "#e02e2a",
            skill: "#b06dff",
          },
          syntax: {
            comment: "#999999",
            string: "#85df7b",
            keyword: "#f67576",
            function: "#b06dff",
            variable: "#fa994c",
            number: "#6dcbf4",
            operator: "#999999",
            tag: "#f67576",
            attribute: "#6dcbf4",
            property: "#999999",
            type: "#b06dff",
            constant: "#6dcbf4",
            invalid: "#ffffff",
          },
        },
        sourceName: "Codex Dark",
      },
    },
  },
  {
    id: "codex-dracula",
    label: "Dracula",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#282a36",
          ink: "#f8f8f2",
          accent: "#ff79c6",
          contrast: 60,
          semanticColors: {
            diffAdded: "#50fa7b",
            diffRemoved: "#ff5555",
            skill: "#ff79c6",
          },
          syntax: {
            comment: "#6272a4",
            string: "#f1fa8c",
            keyword: "#ff79c6",
            function: "#50fa7b",
            variable: "#f8f8f2",
            number: "#bd93f9",
            operator: "#50fa7b",
            tag: "#ff79c6",
            attribute: "#50fa7b",
            property: "#8be9fd",
            type: "#8be9fd",
            constant: "#bd93f9",
            invalid: "#ff5555",
          },
        },
        sourceName: "dracula",
      },
    },
  },
  {
    id: "codex-everforest",
    label: "Everforest",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#fdf6e3",
          ink: "#5c6a72",
          accent: "#93b259",
          contrast: 45,
          semanticColors: {
            diffAdded: "#8da101",
            diffRemoved: "#f85552",
            skill: "#df69ba",
          },
          syntax: {
            comment: "#939f91",
            string: "#dfa000",
            keyword: "#f85552",
            function: "#8da101",
            variable: "#5c6a72",
            number: "#df69ba",
            operator: "#f57d26",
            tag: "#f57d26",
            attribute: "#dfa000",
            property: "#5c6a72",
            type: "#3a94c5",
            constant: "#df69ba",
          },
        },
        sourceName: "everforest-light",
      },
      dark: {
        seed: {
          surface: "#2d353b",
          ink: "#d3c6aa",
          accent: "#a7c080",
          contrast: 60,
          semanticColors: {
            diffAdded: "#a7c080",
            diffRemoved: "#e67e80",
            skill: "#d699b6",
          },
          syntax: {
            comment: "#859289",
            string: "#dbbc7f",
            keyword: "#e67e80",
            function: "#a7c080",
            variable: "#d3c6aa",
            number: "#d699b6",
            operator: "#e69875",
            tag: "#e69875",
            attribute: "#dbbc7f",
            property: "#d3c6aa",
            type: "#7fbbb3",
            constant: "#d699b6",
          },
        },
        sourceName: "everforest-dark",
      },
    },
  },
  {
    id: "codex-github",
    label: "GitHub",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#ffffff",
          ink: "#1f2328",
          accent: "#0969da",
          contrast: 45,
          semanticColors: {
            diffAdded: "#1a7f37",
            diffRemoved: "#cf222e",
            skill: "#8250df",
          },
          syntax: {
            comment: "#6e7781",
            string: "#0a3069",
            keyword: "#cf222e",
            function: "#8250df",
            variable: "#953800",
            number: "#0550ae",
            operator: "#cf222e",
            tag: "#116329",
            attribute: "#0550ae",
            property: "#116329",
            type: "#116329",
            constant: "#0550ae",
            invalid: "#82071e",
          },
        },
        sourceName: "github-light-default",
      },
      dark: {
        seed: {
          surface: "#0d1117",
          ink: "#e6edf3",
          accent: "#1f6feb",
          contrast: 60,
          semanticColors: {
            diffAdded: "#3fb950",
            diffRemoved: "#f85149",
            skill: "#bc8cff",
          },
          syntax: {
            comment: "#8b949e",
            string: "#a5d6ff",
            keyword: "#ff7b72",
            function: "#d2a8ff",
            variable: "#ffa657",
            number: "#79c0ff",
            operator: "#ff7b72",
            tag: "#7ee787",
            attribute: "#79c0ff",
            property: "#7ee787",
            type: "#7ee787",
            constant: "#79c0ff",
            invalid: "#ffa198",
          },
        },
        sourceName: "github-dark-default",
      },
    },
  },
  {
    id: "codex-gruvbox",
    label: "Gruvbox",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#fbf1c7",
          ink: "#3c3836",
          accent: "#458588",
          contrast: 45,
          semanticColors: {
            diffAdded: "#3c3836",
            diffRemoved: "#cc241d",
            skill: "#b16286",
          },
          syntax: {
            comment: "#928374",
            string: "#79740e",
            keyword: "#9d0006",
            function: "#b57614",
            variable: "#076678",
            number: "#8f3f71",
            operator: "#427b58",
            tag: "#427b58",
            attribute: "#b57614",
            property: "#689d6a",
            type: "#b57614",
            constant: "#8f3f71",
            invalid: "#cc241d",
          },
        },
        sourceName: "gruvbox-light-medium",
      },
      dark: {
        seed: {
          surface: "#282828",
          ink: "#ebdbb2",
          accent: "#458588",
          contrast: 60,
          semanticColors: {
            diffAdded: "#ebdbb2",
            diffRemoved: "#cc241d",
            skill: "#b16286",
          },
          syntax: {
            comment: "#928374",
            string: "#b8bb26",
            keyword: "#fb4934",
            function: "#fabd2f",
            variable: "#83a598",
            number: "#d3869b",
            operator: "#8ec07c",
            tag: "#8ec07c",
            attribute: "#fabd2f",
            property: "#689d6a",
            type: "#fabd2f",
            constant: "#d3869b",
            invalid: "#cc241d",
          },
        },
        sourceName: "gruvbox-dark-medium",
      },
    },
  },
  {
    id: "codex-linear",
    label: "Linear",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#fcfcfd",
          ink: "#1b1b1b",
          accent: "#5e6ad2",
          contrast: 45,
          semanticColors: {
            diffAdded: "#52a450",
            diffRemoved: "#c94446",
            skill: "#8160d8",
          },
          syntax: {
            comment: "#8a93a6",
            string: "#0f8f83",
            keyword: "#5e6ad2",
            function: "#8160d8",
            variable: "#2a3140",
            number: "#b4831f",
            operator: "#6f7788",
            attribute: "#0f8f83",
            property: "#2a3140",
            type: "#4380d8",
            constant: "#b4831f",
          },
        },
        sourceName: "Linear Light",
      },
      dark: {
        seed: {
          surface: "#0f0f11",
          ink: "#e3e4e6",
          accent: "#606acc",
          contrast: 60,
          semanticColors: {
            diffAdded: "#69c967",
            diffRemoved: "#ff7e78",
            skill: "#c2a1ff",
          },
          syntax: {
            comment: "#636b7b",
            string: "#7ad9c0",
            keyword: "#8c97ff",
            function: "#c2a1ff",
            variable: "#e6e9ef",
            number: "#f5c56a",
            operator: "#b5bccb",
            attribute: "#7ad9c0",
            property: "#e6e9ef",
            type: "#73b7ff",
            constant: "#f5c56a",
          },
        },
        sourceName: "Linear Dark",
      },
    },
  },
  {
    id: "codex-lobster",
    label: "Lobster",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#111827",
          ink: "#e4e4e7",
          accent: "#ff5c5c",
          contrast: 60,
          semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#ff5c5c",
            skill: "#ff5c5c",
          },
          syntax: {
            comment: "#71717a",
            string: "#14b8a6",
            keyword: "#ff5c5c",
            function: "#22c55e",
            variable: "#e4e4e7",
            number: "#f59e0b",
            operator: "#ff7070",
            attribute: "#14b8a6",
            property: "#e4e4e7",
            type: "#3b82f6",
            constant: "#f59e0b",
            invalid: "#ff5c5c",
          },
        },
        sourceName: "Lobster Dark",
      },
    },
  },
  {
    id: "codex-material",
    label: "Material",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#212121",
          ink: "#eeffff",
          accent: "#80cbc4",
          contrast: 60,
          semanticColors: {
            diffAdded: "#c3e88d",
            diffRemoved: "#f07178",
            skill: "#c792ea",
          },
          syntax: {
            comment: "#545454",
            string: "#c3e88d",
            keyword: "#89ddff",
            function: "#82aaff",
            variable: "#eeffff",
            number: "#f78c6c",
            operator: "#89ddff",
            tag: "#f07178",
            attribute: "#c792ea",
            property: "#f07178",
            type: "#ffcb6b",
            constant: "#89ddff",
          },
        },
        sourceName: "material-theme-darker",
      },
    },
  },
  {
    id: "codex-matrix",
    label: "Matrix",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#040805",
          ink: "#b8ffca",
          accent: "#1eff5a",
          contrast: 60,
          semanticColors: {
            diffAdded: "#1eff5a",
            diffRemoved: "#fa423e",
            skill: "#1eff5a",
          },
          syntax: {
            comment: "#3f8f52",
            string: "#7dff95",
            keyword: "#1eff5a",
            function: "#9bffb8",
            variable: "#b8ffca",
            number: "#55ff7d",
            operator: "#6bd985",
            attribute: "#7dff95",
            property: "#b8ffca",
            type: "#3adf6a",
            constant: "#55ff7d",
          },
        },
        sourceName: "Matrix Dark",
      },
    },
  },
  {
    id: "codex-monokai",
    label: "Monokai",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#272822",
          ink: "#f8f8f2",
          accent: "#99947c",
          contrast: 60,
          semanticColors: {
            diffAdded: "#86b42b",
            diffRemoved: "#c4265e",
            skill: "#8c6bc8",
          },
          syntax: {
            comment: "#88846f",
            string: "#e6db74",
            keyword: "#f92672",
            function: "#a6e22e",
            variable: "#f8f8f2",
            number: "#ae81ff",
            operator: "#f92672",
            tag: "#f92672",
            attribute: "#a6e22e",
            property: "#66d9ef",
            type: "#a6e22e",
            constant: "#ae81ff",
            invalid: "#f44747",
          },
        },
        sourceName: "monokai",
      },
    },
  },
  {
    id: "codex-night-owl",
    label: "Night Owl",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#011627",
          ink: "#d6deeb",
          accent: "#44596b",
          contrast: 60,
          semanticColors: {
            diffAdded: "#c5e478",
            diffRemoved: "#ef5350",
            skill: "#c792ea",
          },
          syntax: {
            comment: "#637777",
            string: "#ecc48d",
            keyword: "#c792ea",
            function: "#c792ea",
            variable: "#c5e478",
            number: "#f78c6c",
            operator: "#7fdbca",
            tag: "#caece6",
            attribute: "#c5e478",
            property: "#80cbc4",
            type: "#c5e478",
            constant: "#82aaff",
            invalid: "#ffffff",
          },
        },
        sourceName: "night-owl",
      },
    },
  },
  {
    id: "codex-nord",
    label: "Nord",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#2e3440",
          ink: "#d8dee9",
          accent: "#88c0d0",
          contrast: 60,
          semanticColors: {
            diffAdded: "#a3be8c",
            diffRemoved: "#bf616a",
            skill: "#b48ead",
          },
          syntax: {
            comment: "#616e88",
            string: "#a3be8c",
            keyword: "#81a1c1",
            function: "#88c0d0",
            variable: "#d8dee9",
            number: "#b48ead",
            operator: "#81a1c1",
            tag: "#81a1c1",
            attribute: "#8fbcbb",
            property: "#8fbcbb",
            type: "#8fbcbb",
            constant: "#81a1c1",
            invalid: "#d8dee9",
          },
        },
        sourceName: "nord",
      },
    },
  },
  {
    id: "codex-notion",
    label: "Notion",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#ffffff",
          ink: "#37352f",
          accent: "#3183d8",
          contrast: 45,
          semanticColors: {
            diffAdded: "#00a240",
            diffRemoved: "#ba2623",
            skill: "#3183d8",
          },
          syntax: {
            comment: "#008000",
            string: "#a31515",
            keyword: "#0000ff",
            function: "#795e26",
            variable: "#37352f",
            number: "#098658",
            operator: "#37352f",
            property: "#37352f",
            type: "#267f99",
            constant: "#098658",
          },
        },
        sourceName: "Notion Light",
      },
      dark: {
        seed: {
          surface: "#191919",
          ink: "#d9d9d8",
          accent: "#3183d8",
          contrast: 60,
          semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#fa423e",
            skill: "#3183d8",
          },
          syntax: {
            comment: "#6a9955",
            string: "#ce9178",
            keyword: "#569cd6",
            function: "#dcdcaa",
            variable: "#d9d9d8",
            number: "#b5cea8",
            operator: "#d4d4d4",
            property: "#d9d9d8",
            type: "#4ec9b0",
            constant: "#b5cea8",
          },
        },
        sourceName: "Notion Dark",
      },
    },
  },
  {
    id: "codex-oscurange",
    label: "Oscurange",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#0b0b0f",
          ink: "#e6e6e6",
          accent: "#f9b98c",
          contrast: 60,
          semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#fa423e",
            skill: "#f9b98c",
          },
          syntax: {
            comment: "#46474f",
            string: "#e6e6e6",
            keyword: "#9099a1",
            function: "#f9b98c",
            variable: "#e6e6e6",
            number: "#f9b98c",
            operator: "#9099a1",
            tag: "#f9b98c",
            attribute: "#9099a1",
            property: "#e6e6e6",
            type: "#9592a4",
            constant: "#f9b98c",
          },
        },
        sourceName: "Oscurange",
      },
    },
  },
  {
    id: "codex-one",
    label: "One",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#fafafa",
          ink: "#383a42",
          accent: "#526fff",
          contrast: 45,
          semanticColors: {
            diffAdded: "#3bba54",
            diffRemoved: "#ba2623",
            skill: "#526fff",
          },
          syntax: {
            comment: "#a0a1a7",
            string: "#50a14f",
            keyword: "#a626a4",
            function: "#4078f2",
            variable: "#e45649",
            number: "#986801",
            operator: "#383a42",
            tag: "#e45649",
            attribute: "#986801",
            property: "#383a42",
            type: "#c18401",
            constant: "#986801",
            invalid: "#50a14f",
          },
        },
        sourceName: "one-light",
      },
      dark: {
        seed: {
          surface: "#282c34",
          ink: "#abb2bf",
          accent: "#4d78cc",
          contrast: 60,
          semanticColors: {
            diffAdded: "#8cc265",
            diffRemoved: "#e05561",
            skill: "#c162de",
          },
          syntax: {
            comment: "#7f848e",
            string: "#98c379",
            keyword: "#c678dd",
            function: "#61afef",
            variable: "#e06c75",
            number: "#d19a66",
            operator: "#abb2bf",
            tag: "#e06c75",
            attribute: "#d19a66",
            property: "#abb2bf",
            type: "#e5c07b",
            constant: "#56b6c2",
            invalid: "#ffffff",
          },
        },
        sourceName: "one-dark-pro",
      },
    },
  },
  {
    id: "codex-proof",
    label: "Proof",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#f5f3ed",
          ink: "#2f312d",
          accent: "#3d755d",
          contrast: 45,
          semanticColors: {
            diffAdded: "#3d755d",
            diffRemoved: "#ba2623",
            skill: "#3d755d",
          },
          syntax: {
            comment: "#8b877c",
            string: "#3d755d",
            keyword: "#5f6ac2",
            function: "#3d755d",
            variable: "#2f312d",
            number: "#d3b45b",
            operator: "#7a766d",
            property: "#2f312d",
            type: "#5f6ac2",
            constant: "#d3b45b",
          },
        },
        sourceName: "Proof Light",
      },
    },
  },
  {
    id: "codex-raycast",
    label: "Raycast",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#ffffff",
          ink: "#030303",
          accent: "#ff6363",
          contrast: 45,
          semanticColors: {
            diffAdded: "#006b4f",
            diffRemoved: "#b12424",
            skill: "#9a1b6e",
          },
          syntax: {
            comment: "#999999",
            string: "#c03030",
            keyword: "#666666",
            function: "#c75d07",
            variable: "#000000",
            number: "#000000",
            operator: "#000000",
            tag: "#c75d07",
            attribute: "#c75d07",
            property: "#666666",
            type: "#c75d07",
            constant: "#000000",
          },
        },
        sourceName: "Raycast Light",
      },
      dark: {
        seed: {
          surface: "#101010",
          ink: "#fefefe",
          accent: "#ff6363",
          contrast: 60,
          semanticColors: {
            diffAdded: "#59d499",
            diffRemoved: "#ff6363",
            skill: "#cf2f98",
          },
          syntax: {
            comment: "#666666",
            string: "#ff6363",
            keyword: "#999999",
            function: "#ff9217",
            variable: "#ffffff",
            number: "#ffffff",
            operator: "#ffffff",
            tag: "#ff6363",
            attribute: "#ff9217",
            property: "#999999",
            type: "#ff9217",
            constant: "#ffffff",
          },
        },
        sourceName: "Raycast Dark",
      },
    },
  },
  {
    id: "codex-rose-pine",
    label: "Rose Pine",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#faf4ed",
          ink: "#575279",
          accent: "#d7827e",
          contrast: 45,
          semanticColors: {
            diffAdded: "#56949f",
            diffRemoved: "#797593",
            skill: "#907aa9",
          },
          syntax: {
            comment: "#9893a5",
            string: "#ea9d34",
            keyword: "#286983",
            function: "#b4637a",
            variable: "#d7827e",
            number: "#d7827e",
            operator: "#286983",
            tag: "#56949f",
            attribute: "#907aa9",
            property: "#575279",
            type: "#56949f",
            constant: "#d7827e",
            invalid: "#b4637a",
          },
        },
        sourceName: "rose-pine-dawn",
      },
      dark: {
        seed: {
          surface: "#232136",
          ink: "#e0def4",
          accent: "#ea9a97",
          contrast: 60,
          semanticColors: {
            diffAdded: "#9ccfd8",
            diffRemoved: "#908caa",
            skill: "#c4a7e7",
          },
          syntax: {
            comment: "#6e6a86",
            string: "#f6c177",
            keyword: "#3e8fb0",
            function: "#eb6f92",
            variable: "#ea9a97",
            number: "#ea9a97",
            operator: "#3e8fb0",
            tag: "#9ccfd8",
            attribute: "#c4a7e7",
            property: "#e0def4",
            type: "#9ccfd8",
            constant: "#ea9a97",
            invalid: "#eb6f92",
          },
        },
        sourceName: "rose-pine-moon",
      },
    },
  },
  {
    id: "codex-sentry",
    label: "Sentry",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#2d2935",
          ink: "#e6dff9",
          accent: "#7055f6",
          contrast: 60,
          semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#fa423e",
            skill: "#7055f6",
          },
          syntax: {
            comment: "#8d849f",
            string: "#8ee6d7",
            keyword: "#7055f6",
            function: "#a58cff",
            variable: "#e6dff9",
            number: "#f4c46a",
            operator: "#c8bedf",
            attribute: "#8ee6d7",
            property: "#e6dff9",
            type: "#c39bff",
            constant: "#f4c46a",
          },
        },
        sourceName: "Sentry Dark",
      },
    },
  },
  {
    id: "codex-solarized",
    label: "Solarized",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#fdf6e3",
          ink: "#657b83",
          accent: "#b58900",
          contrast: 45,
          semanticColors: {
            diffAdded: "#859900",
            diffRemoved: "#dc322f",
            skill: "#d33682",
          },
          syntax: {
            comment: "#93a1a1",
            string: "#2aa198",
            keyword: "#859900",
            function: "#268bd2",
            variable: "#268bd2",
            number: "#d33682",
            operator: "#859900",
            tag: "#268bd2",
            attribute: "#93a1a1",
            property: "#859900",
            type: "#cb4b16",
            constant: "#b58900",
            invalid: "#dc322f",
          },
        },
        sourceName: "solarized-light",
      },
      dark: {
        seed: {
          surface: "#002b36",
          ink: "#839496",
          accent: "#d30102",
          contrast: 60,
          semanticColors: {
            diffAdded: "#859900",
            diffRemoved: "#dc322f",
            skill: "#d33682",
          },
          syntax: {
            comment: "#586e75",
            string: "#2aa198",
            keyword: "#859900",
            function: "#268bd2",
            variable: "#268bd2",
            number: "#d33682",
            operator: "#859900",
            tag: "#268bd2",
            attribute: "#93a1a1",
            property: "#859900",
            type: "#cb4b16",
            constant: "#b58900",
            invalid: "#dc322f",
          },
        },
        sourceName: "solarized-dark",
      },
    },
  },
  {
    id: "codex-tokyo-night",
    label: "Tokyo Night",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#1a1b26",
          ink: "#a9b1d6",
          accent: "#3d59a1",
          contrast: 60,
          semanticColors: {
            diffAdded: "#449dab",
            diffRemoved: "#914c54",
            skill: "#9d7cd8",
          },
          syntax: {
            comment: "#51597d",
            string: "#9ece6a",
            keyword: "#bb9af7",
            function: "#7aa2f7",
            variable: "#c0caf5",
            number: "#ff9e64",
            operator: "#89ddff",
            tag: "#f7768e",
            attribute: "#bb9af7",
            property: "#7dcfff",
            type: "#0db9d7",
            constant: "#ff9e64",
            invalid: "#ff5370",
          },
        },
        sourceName: "tokyo-night",
      },
    },
  },
  {
    id: "codex-temple",
    label: "Temple",
    source: "codex",
    variants: {
      dark: {
        seed: {
          surface: "#02120c",
          ink: "#c7e6da",
          accent: "#e4f222",
          contrast: 60,
          semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#fa423e",
            skill: "#e4f222",
          },
          syntax: {
            comment: "#394d46",
            string: "#e4f222",
            keyword: "#e4f222",
            function: "#e4f222",
            variable: "#c7e6da",
            number: "#e4f222",
            operator: "#788617",
            attribute: "#788617",
            property: "#c7e6da",
            type: "#859419",
            constant: "#e4f222",
          },
        },
        sourceName: "Temple Dark",
      },
    },
  },
  {
    id: "codex-vercel",
    label: "Vercel",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#ffffff",
          ink: "#171717",
          accent: "#006aff",
          contrast: 40,
          semanticColors: {
            diffAdded: "#28a948",
            diffRemoved: "#eb001d",
            skill: "#a100f8",
          },
          syntax: {
            comment: "#666666",
            string: "#28a948",
            keyword: "#006aff",
            function: "#a100f8",
            variable: "#171717",
            number: "#a100f8",
            operator: "#666666",
            attribute: "#28a948",
            property: "#171717",
            type: "#0059d1",
            constant: "#a100f8",
          },
        },
        sourceName: "Vercel Light",
      },
      dark: {
        seed: {
          surface: "#000000",
          ink: "#ededed",
          accent: "#006efe",
          contrast: 50,
          semanticColors: {
            diffAdded: "#00ad3a",
            diffRemoved: "#f13342",
            skill: "#9540d5",
          },
          syntax: {
            comment: "#666666",
            string: "#00ad3a",
            keyword: "#006efe",
            function: "#9540d5",
            variable: "#ededed",
            number: "#9540d5",
            operator: "#a1a1a1",
            attribute: "#00ad3a",
            property: "#ededed",
            type: "#52a8ff",
            constant: "#9540d5",
          },
        },
        sourceName: "Vercel Dark",
      },
    },
  },
  {
    id: "codex-vscode-plus",
    label: "VS Code Plus",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#ffffff",
          ink: "#000000",
          accent: "#007acc",
          contrast: 45,
          semanticColors: {
            diffAdded: "#369432",
            diffRemoved: "#c72e0f",
            skill: "#90c2f9",
          },
          syntax: {
            comment: "#008000",
            string: "#a31515",
            keyword: "#0000ff",
            function: "#795e26",
            variable: "#001080",
            number: "#098658",
            operator: "#000000",
            tag: "#800000",
            attribute: "#e50000",
            property: "#e50000",
            type: "#267f99",
            constant: "#0000ff",
            invalid: "#cd3131",
          },
        },
        sourceName: "light-plus",
      },
      dark: {
        seed: {
          surface: "#1e1e1e",
          ink: "#d4d4d4",
          accent: "#007acc",
          contrast: 60,
          semanticColors: {
            diffAdded: "#369432",
            diffRemoved: "#fa423e",
            skill: "#add6ff",
          },
          syntax: {
            comment: "#6a9955",
            string: "#ce9178",
            keyword: "#569cd6",
            function: "#dcdcaa",
            variable: "#9cdcfe",
            number: "#b5cea8",
            operator: "#d4d4d4",
            tag: "#569cd6",
            attribute: "#9cdcfe",
            property: "#9cdcfe",
            type: "#4ec9b0",
            constant: "#569cd6",
            invalid: "#f44747",
          },
        },
        sourceName: "dark-plus",
      },
    },
  },
  {
    id: "codex-xcode",
    label: "Xcode",
    source: "codex",
    variants: {
      light: {
        seed: {
          surface: "#ffffff",
          ink: "#000000",
          accent: "#0e0eff",
          contrast: 45,
          semanticColors: {
            diffAdded: "#00a240",
            diffRemoved: "#ba2623",
            skill: "#0e0eff",
          },
          syntax: {
            comment: "#5d6c79",
            string: "#c41a16",
            keyword: "#9b2393",
            function: "#326d74",
            variable: "#326d74",
            number: "#1c00cf",
            operator: "#9b2393",
            property: "#0b4f79",
            type: "#0b4f79",
            constant: "#1c00cf",
          },
        },
        sourceName: "Xcode Light",
      },
      dark: {
        seed: {
          surface: "#1f1f24",
          ink: "#ffffff",
          accent: "#5482ff",
          contrast: 60,
          semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#fa423e",
            skill: "#5482ff",
          },
          syntax: {
            comment: "#6c7986",
            string: "#fc6a5d",
            keyword: "#fc5fa3",
            function: "#67b7a4",
            variable: "#67b7a4",
            number: "#d0bf69",
            operator: "#fc5fa3",
            property: "#5dd8ff",
            type: "#5dd8ff",
            constant: "#d0bf69",
          },
        },
        sourceName: "Xcode Dark",
      },
    },
  },
];
