//! Typed Agent Org messaging primitives + persistent inbox.
//!
//! Substrate for inter-agent communication inside an `AgentOrgRun`. Uses
//! a typed enum (`AgentMessage`) persisted to a SQLite table
//! (`agent_inbox`). An in-process delivery channel layers on top of the
//! same store, and the sidechain-resume drain path consumes it.
//!
//! ## NOT to be confused with the `inbox` crate
//!
//! The `inbox` crate is the **user-facing** inbox: notifications and summaries
//! that an agent posts to the human via `send_to_inbox`. This module is the
//! **agent-to-agent** inbox: typed messages exchanged between sibling agents
//! inside the same `AgentOrgRun`. Different audience, different lifecycle,
//! different schema — they intentionally do not share storage or types.
//!
//! ## Design notes
//! - `AgentMessage` is a discriminated union. `Plain` is the only free-form
//!   text variant; the rest are typed RPCs that downstream code can pattern
//!   match on without re-parsing strings.
//! - Persistence stores the variant tag (`payload_kind`) alongside the
//!   serialised payload so debug / migration paths can introspect without a
//!   full JSON walk. The `payload_kind` column MUST stay in sync with the
//!   serde `tag = "kind"` on `AgentMessage` — see the `kind_tag_matches_serde_tag`
//!   regression test below.

use rusqlite::{params, Connection, Result as SqliteResult};
use serde::{Deserialize, Serialize};

use crate::session::AgentExecMode;
use database::db::{get_connection, with_sessions_writer};

pub fn is_supported_agent_org_remote_mode(mode: AgentExecMode) -> bool {
    matches!(
        mode,
        AgentExecMode::Build | AgentExecMode::Ask | AgentExecMode::Plan
    )
}

/// Reserved sender id for system-generated agent inbox rows.
///
/// Used by:
/// - [`AgentMessage::MemberTerminated`] — inbox-drain side-effect path
///   stamps it after observing a `ShutdownResponse{accepted=true}` and
///   cancelling the member's session.
/// - [`AgentMessage::MemberIdle`] — coordinator-side idle hook stamps
///   it when a member session transitions to idle / interrupted /
///   failed at the turn-finalize boundary.
///
/// These are out-of-band notifications — no LLM originated them — so the
/// sender field gets a marker that cannot collide with any real
/// `agent_id` (those are UUIDs / human-chosen names).
pub const SYSTEM_SENDER_ID: &str = "_system";
pub const USER_SENDER_ID: &str = "_user";

/// Wrapper around a UUID-ish string that correlates a request to a response.
///
/// Always client-generated by the sender (the LLM, in practice — it picks
/// the id and echoes it on the response). Required for every RPC-style
/// variant (`*Request`, `*Response`); ignored for `Plain` and one-shot
/// notifications.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RequestId(pub String);

impl RequestId {
    /// Generate a fresh UUID-backed id. Used by tests today and by the
    /// response path (auto-correlation when a worker replies via a
    /// non-LLM source, e.g. an internal cancellation timeout).
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for RequestId {
    fn default() -> Self {
        Self::new()
    }
}

/// Typed message payload exchanged between agents inside an `AgentOrgRun`.
///
/// Each variant has its own validation rules — see [`AgentMessage::validate`].
///
/// ## Why so few variants
/// We deliberately keep this enum minimal. orgii already has a permission
/// system (`interaction::permission`) and a mode-switch system
/// (`interaction::mode_switch`) that talk to the **user**, not other agents.
/// A second agent-bus shadow of those would be a parallel implementation
/// with no real receiver. Only variants with a concrete caller AND a
/// concrete recipient outcome survive:
///
///   * `Plain` — free-form text (the common case).
///   * `Shutdown{Request,Response}` — graceful coordinator-driven worker
///     termination.
///   * `PlanApproval{Request,Response}` — a planning task assignment starts
///     the member in Plan mode automatically. `create_plan` persists a
///     task-bound approval; coordinator rejection is delivered as a
///     `PlanApprovalResponse` so the member can revise. Approval itself
///     completes the planning task and unlocks dependent work, without a
///     fake Build turn for the Planner.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind")]
pub enum AgentMessage {
    /// Free-form text. `summary` is a short label used in tool listings;
    /// `text` is the body delivered into the recipient's transcript.
    Plain { summary: String, text: String },

    /// Coordinator → worker: please wind down and exit. Response is
    /// `ShutdownResponse`.
    ShutdownRequest {
        request_id: RequestId,
        reason: Option<String>,
    },
    ShutdownResponse {
        request_id: RequestId,
        accepted: bool,
        note: Option<String>,
    },

    /// Member → coordinator: "I drafted a plan, please approve."
    /// Sent by `create_plan` when the calling session participates in
    /// an org and is not the coordinator. The coordinator's LLM is
    /// expected to reply with `PlanApprovalResponse` echoing the same
    /// `request_id`.
    ///
    /// `plan_path` is the absolute path to the plan markdown file on
    /// disk so the coordinator can read it directly with `read_file`
    /// if the inline `plan_content` excerpt is not enough. `plan_title`
    /// is the human-friendly label used by `create_plan`.
    PlanApprovalRequest {
        request_id: RequestId,
        approval_id: String,
        plan_revision_id: String,
        source_task_id: String,
        plan_title: String,
        plan_path: String,
        plan_content: String,
    },

    /// Coordinator → member: "I reviewed your plan."
    ///
    /// New rows are used for rejection/revision: `accepted = false` keeps
    /// the member in Plan mode. Deserializing accepted responses remains
    /// supported for historical inbox rows created before task-bound
    /// approvals; their `next_mode` defaults to Build.
    PlanApprovalResponse {
        request_id: RequestId,
        accepted: bool,
        feedback: Option<String>,
        next_mode: Option<AgentExecMode>,
    },

    /// System → coordinator: "member `<member_id>` (a.k.a. `<member_name>`)
    /// has been terminated."
    ///
    /// Emitted by the coordinator-side inbox-drain side-effect path
    /// when it observes a `ShutdownResponse{accepted=true}` from a
    /// member (after issuing `cancel_session` on the member's runtime).
    /// Without it the coordinator's LLM has no signal that the worker
    /// is gone and may keep dispatching tasks into a dead inbox.
    ///
    /// Not LLM-callable: `org_send_message` rejects this kind, and the
    /// `sender_agent_id` of the inbox row MUST equal [`SYSTEM_SENDER_ID`]
    /// (`"_system"`) so a member cannot forge another member's termination
    /// notification. Both invariants are pinned by unit + E2E tests.
    MemberTerminated {
        member_id: String,
        member_name: String,
        reason: MemberTerminationReason,
    },

    /// System → coordinator: "member `<agent_id>` is idle."
    ///
    /// Emitted at every member transition to idle so the coordinator's
    /// LLM has a positive signal that the worker finished its current
    /// turn / errored out / was interrupted, instead of having to poll
    /// session status out-of-band.
    ///
    /// Uses the same system-sender pattern as `MemberTerminated` so
    /// the worker session
    /// does not need a write handle into another session's inbox table.
    /// The coordinator-side hook in `inbox_drain` observes member-session
    /// finalize transitions and stamps the row with [`SYSTEM_SENDER_ID`].
    ///
    /// The fields cover everything orgii can faithfully populate: who,
    /// why, and the optional last-message summary the LLM uses to
    /// compose its next dispatch.
    ///
    /// Not LLM-callable: `org_send_message` rejects this kind for the
    /// same reasoning as `MemberTerminated` — allowing a member to forge
    /// peer-idle notifications would let it spoof another member's
    /// completion state and trick the coordinator into double-dispatch.
    MemberIdle {
        member_id: String,
        member_name: String,
        reason: MemberIdleReason,
        /// Execution mode the member ended the turn in. This is
        /// coordinator-facing evidence for remote mode control: after an
        /// `exec_mode_set_request`, the next `member_idle` row should show
        /// the mode that actually ran.
        current_mode: Option<AgentExecMode>,
        /// Short XML-safe blurb extracted from the member's last
        /// outbound DM this turn. `None` is allowed — turn end without
        /// an outbound DM is a valid (and common) idle transition.
        summary: Option<String>,
        /// Free-form runtime error string when `reason == Failed`.
        /// Required iff `Failed`; rejected otherwise. Validated by
        /// [`AgentMessage::validate`].
        failure_reason: Option<String>,
        /// Build tasks that still remain `in_progress` even though this
        /// member has reached an idle turn boundary. Kept separate from
        /// `reason`: session availability and task finality are independent.
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        unfinished_task_ids: Vec<String>,
    },

    /// System → owner: "you have been assigned task `<task_id>`."
    ///
    /// Emitted whenever an authorized task mutation explicitly sets or
    /// changes a task's `owner` field.
    ///
    /// This row is enqueued by the `task_create`/`task_update` LLM
    /// tools and assignment recovery. It is *not* LLM-callable
    /// via `org_send_message` — fabricating an assignment would let
    /// any member redirect the coordinator's task graph. The producer
    /// stamps `sender_agent_id` with whoever caused the assignment (the
    /// assigning member's `agent_id`, or [`SYSTEM_SENDER_ID`] for
    /// scheduler redelivery of an existing explicit assignment).
    ///
    /// `subject` / `description` are denormalized snapshots of the
    /// assigned [`agent_org_tasks::Task`](super::agent_org_tasks::Task)
    /// row at the moment of assignment, so the recipient's LLM can
    /// render the assignment in the inbox-drain prompt without an extra
    /// store lookup. The authoritative copy lives in `agent_org_tasks`.
    /// `assigned_by` is the human-readable display name; the wire-level
    /// identity of the producer is `sender_agent_id` on the row.
    TaskAssigned {
        task_id: String,
        subject: String,
        description: String,
        assigned_by: String,
        /// Task-scoped execution mode chosen by the coordinator. Historical
        /// rows without this field retain Build semantics.
        #[serde(default = "default_task_execution_mode")]
        execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode,
        /// Durable outputs of every completed blocker, copied into the
        /// assignment so the recipient never needs another session's chat.
        #[serde(default)]
        dependency_outputs: Vec<TaskDependencyOutput>,
    },

    /// System → coordinator: an owner persisted a completed task and its
    /// durable output. Unlike `MemberIdle`, this is a task fact, not a session
    /// liveness hint, so the coordinator can immediately refresh the board.
    TaskCompleted {
        task_id: String,
        subject: String,
        completed_by_member_id: String,
        output_summary: Option<String>,
        remaining_open_task_count: usize,
    },

    /// Historical coordinator → member execution-mode request.
    ///
    /// New Agent Org task assignments carry `execution_mode` directly and
    /// `org_send_message` no longer exposes this variant to the LLM. It stays
    /// deserializable so inbox rows created by older builds remain readable.
    /// The member's drain applies it before the next turn starts, and the next
    /// `MemberIdle` carries the mode the member actually ended the turn in (the LLM can read that to
    /// confirm the switch took).
    ///
    /// `reason` is an optional human blurb the recipient can echo into
    /// its system prompt the same turn (mirrors how
    /// `PlanApprovalResponse.feedback` is wired). Bounded length so a
    /// runaway prompt cannot blow up history.
    ExecModeSetRequest {
        request_id: RequestId,
        mode: AgentExecMode,
        reason: Option<String>,
    },
}

fn default_task_execution_mode() -> crate::coordination::agent_org_tasks::TaskExecutionMode {
    crate::coordination::agent_org_tasks::TaskExecutionMode::Build
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct TaskDependencyOutput {
    pub task_id: String,
    pub subject: String,
    pub summary: String,
    pub content: Option<String>,
    pub artifact_ids: Vec<String>,
    pub produced_by_member_id: String,
}

/// Why a member was terminated. Stable wire string so coordinator-side
/// LLM prompts can branch on it without re-parsing freeform text.
///
/// Today the only producer is the shutdown-handshake side-effect path, so
/// only the `Shutdown` variant is emitted. Other reasons (crash, cancel,
/// timeout) are reserved for follow-up phases.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemberTerminationReason {
    /// The member acknowledged a shutdown request (or volunteered one)
    /// via `ShutdownResponse{accepted=true}`, and the coordinator-side
    /// drain cancelled the session in response. This is the protocol
    /// happy path.
    Shutdown,
}

/// Why a member became idle.
///
/// `Available` — the member finished its turn cleanly and is ready for
/// the next dispatch. `Interrupted` — a user/coordinator cancel landed
/// mid-turn. `Failed` — the member hit a runtime error during the turn
/// and surfaces `failure_reason` for the coordinator's LLM.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemberIdleReason {
    Available,
    Interrupted,
    Failed,
}

impl AgentMessage {
    /// Stable discriminator string persisted alongside the JSON payload.
    /// Must round-trip with the serde tag; if the enum is renamed, update
    /// both sides simultaneously.
    pub fn kind_tag(&self) -> &'static str {
        match self {
            Self::Plain { .. } => "plain",
            Self::ShutdownRequest { .. } => "shutdown_request",
            Self::ShutdownResponse { .. } => "shutdown_response",
            Self::PlanApprovalRequest { .. } => "plan_approval_request",
            Self::PlanApprovalResponse { .. } => "plan_approval_response",
            Self::MemberTerminated { .. } => "member_terminated",
            Self::MemberIdle { .. } => "member_idle",
            Self::TaskAssigned { .. } => "task_assigned",
            Self::TaskCompleted { .. } => "task_completed",
            Self::ExecModeSetRequest { .. } => "exec_mode_set_request",
        }
    }

    /// `RequestId` carried by RPC variants, if any.
    pub fn request_id(&self) -> Option<&RequestId> {
        match self {
            Self::ShutdownRequest { request_id, .. }
            | Self::ShutdownResponse { request_id, .. }
            | Self::PlanApprovalRequest { request_id, .. }
            | Self::PlanApprovalResponse { request_id, .. }
            | Self::ExecModeSetRequest { request_id, .. } => Some(request_id),
            Self::Plain { .. }
            | Self::MemberTerminated { .. }
            | Self::MemberIdle { .. }
            | Self::TaskAssigned { .. }
            | Self::TaskCompleted { .. } => None,
        }
    }

    /// Whether this variant carries an RPC-style structured payload (vs
    /// plain free-form text). Used by `org_send_message` to enforce the
    /// "broadcast must be plain only" invariant — structured RPCs need a
    /// 1:1 correlation between sender and recipient via `request_id`,
    /// which is incoherent with fan-out.
    ///
    /// `MemberTerminated` is structured (typed payload, system-emitted),
    /// even though it has no `request_id`: the broadcast guard rejects
    /// it because broadcasting a member-termination notice to every member
    /// is nonsensical, and `org_send_message` rejects it outright as
    /// non-LLM-callable.
    pub fn is_structured(&self) -> bool {
        match self {
            Self::Plain { .. } => false,
            Self::ShutdownRequest { .. }
            | Self::ShutdownResponse { .. }
            | Self::PlanApprovalRequest { .. }
            | Self::PlanApprovalResponse { .. }
            | Self::MemberTerminated { .. }
            | Self::MemberIdle { .. }
            | Self::TaskAssigned { .. }
            | Self::TaskCompleted { .. }
            | Self::ExecModeSetRequest { .. } => true,
        }
    }

    /// Validate variant invariants prior to persistence.
    ///
    /// Returns a stable error string suitable to surface back to the LLM
    /// via tool error reporting.
    pub fn validate(&self) -> Result<(), String> {
        match self {
            Self::Plain { summary, text } => {
                if summary.trim().is_empty() {
                    return Err("Plain.summary must not be empty".into());
                }
                if text.trim().is_empty() {
                    return Err("Plain.text must not be empty".into());
                }
                if summary.len() > 200 {
                    return Err("Plain.summary must be ≤ 200 chars".into());
                }
            }
            Self::ShutdownRequest { request_id, .. }
            | Self::ShutdownResponse { request_id, .. } => {
                if request_id.as_str().trim().is_empty() {
                    return Err("request_id must not be empty".into());
                }
            }
            Self::PlanApprovalRequest {
                request_id,
                approval_id,
                plan_revision_id,
                source_task_id,
                plan_title,
                plan_path,
                plan_content,
            } => {
                if request_id.as_str().trim().is_empty() {
                    return Err("request_id must not be empty".into());
                }
                if plan_title.trim().is_empty() {
                    return Err("PlanApprovalRequest.plan_title must not be empty".into());
                }
                if approval_id.trim().is_empty()
                    || plan_revision_id.trim().is_empty()
                    || source_task_id.trim().is_empty()
                {
                    return Err(
                        "PlanApprovalRequest requires approval_id, plan_revision_id, and source_task_id"
                            .into(),
                    );
                }
                if plan_path.trim().is_empty() {
                    return Err("PlanApprovalRequest.plan_path must not be empty".into());
                }
                if plan_content.trim().is_empty() {
                    return Err("PlanApprovalRequest.plan_content must not be empty".into());
                }
                if plan_content.chars().count() > 20_000 {
                    return Err(
                        "PlanApprovalRequest.plan_content must be ≤ 20000 chars; use plan_path for the full plan"
                            .into(),
                    );
                }
            }
            Self::PlanApprovalResponse {
                request_id,
                next_mode,
                ..
            } => {
                if request_id.as_str().trim().is_empty() {
                    return Err("request_id must not be empty".into());
                }
                if let Some(mode) = next_mode {
                    if !is_supported_agent_org_remote_mode(*mode) {
                        return Err(
                            "PlanApprovalResponse.next_mode must be one of: build, ask, plan"
                                .into(),
                        );
                    }
                }
            }
            Self::MemberTerminated {
                member_id,
                member_name,
                ..
            } => {
                if member_id.trim().is_empty() {
                    return Err("MemberTerminated.member_id must not be empty".into());
                }
                if member_name.trim().is_empty() {
                    return Err("MemberTerminated.member_name must not be empty".into());
                }
            }
            Self::MemberIdle {
                member_id,
                member_name,
                reason,
                summary,
                failure_reason,
                unfinished_task_ids,
                ..
            } => {
                if member_id.trim().is_empty() {
                    return Err("MemberIdle.member_id must not be empty".into());
                }
                if member_name.trim().is_empty() {
                    return Err("MemberIdle.member_name must not be empty".into());
                }
                if let Some(s) = summary {
                    if s.len() > 500 {
                        return Err("MemberIdle.summary must be ≤ 500 chars".into());
                    }
                }
                if unfinished_task_ids.len() > 32
                    || unfinished_task_ids
                        .iter()
                        .any(|task_id| task_id.trim().is_empty() || task_id.len() > 200)
                {
                    return Err(
                        "MemberIdle.unfinished_task_ids must contain at most 32 non-empty task ids of ≤ 200 chars"
                            .into(),
                    );
                }
                match reason {
                    MemberIdleReason::Failed => {
                        let fr = failure_reason.as_deref().unwrap_or("").trim();
                        if fr.is_empty() {
                            return Err(
                                "MemberIdle.failure_reason is required when reason='failed'".into(),
                            );
                        }
                    }
                    MemberIdleReason::Available | MemberIdleReason::Interrupted => {
                        if failure_reason.is_some() {
                            return Err(
                                "MemberIdle.failure_reason is only valid when reason='failed'"
                                    .into(),
                            );
                        }
                    }
                }
            }
            Self::TaskAssigned {
                task_id,
                subject,
                assigned_by,
                description,
                dependency_outputs,
                ..
            } => {
                if task_id.trim().is_empty() {
                    return Err("TaskAssigned.task_id must not be empty".into());
                }
                if subject.trim().is_empty() {
                    return Err("TaskAssigned.subject must not be empty".into());
                }
                if assigned_by.trim().is_empty() {
                    return Err("TaskAssigned.assigned_by must not be empty".into());
                }
                if subject.len() > 200 {
                    return Err("TaskAssigned.subject must be ≤ 200 chars".into());
                }
                if description.len() > 4000 {
                    return Err("TaskAssigned.description must be ≤ 4000 chars".into());
                }
                for output in dependency_outputs {
                    if output.task_id.trim().is_empty()
                        || output.subject.trim().is_empty()
                        || output.summary.trim().is_empty()
                        || output.produced_by_member_id.trim().is_empty()
                    {
                        return Err(
                            "TaskAssigned.dependency_outputs entries require task_id, subject, summary, and produced_by_member_id"
                                .into(),
                        );
                    }
                    if output
                        .content
                        .as_ref()
                        .is_some_and(|content| content.chars().count() > 20_000)
                    {
                        return Err(
                            "TaskAssigned.dependency_outputs content must be ≤ 20000 chars".into(),
                        );
                    }
                }
                let total_inline_chars: usize = dependency_outputs
                    .iter()
                    .filter_map(|output| output.content.as_ref())
                    .map(|content| content.chars().count())
                    .sum();
                if total_inline_chars > 50_000 {
                    return Err(
                        "TaskAssigned.dependency_outputs total inline content must be ≤ 50000 chars; use artifacts for larger handoffs"
                            .into(),
                    );
                }
            }
            Self::TaskCompleted {
                task_id,
                subject,
                completed_by_member_id,
                output_summary,
                ..
            } => {
                if task_id.trim().is_empty() {
                    return Err("TaskCompleted.task_id must not be empty".into());
                }
                if subject.trim().is_empty() {
                    return Err("TaskCompleted.subject must not be empty".into());
                }
                if completed_by_member_id.trim().is_empty() {
                    return Err("TaskCompleted.completed_by_member_id must not be empty".into());
                }
                if output_summary
                    .as_ref()
                    .is_some_and(|summary| summary.chars().count() > 1_000)
                {
                    return Err("TaskCompleted.output_summary must be ≤ 1000 chars".into());
                }
            }
            Self::ExecModeSetRequest {
                request_id,
                mode,
                reason,
            } => {
                if request_id.as_str().trim().is_empty() {
                    return Err("ExecModeSetRequest.request_id must not be empty".into());
                }
                if !is_supported_agent_org_remote_mode(*mode) {
                    return Err("ExecModeSetRequest.mode must be one of: build, ask, plan".into());
                }
                if let Some(r) = reason {
                    if r.len() > 500 {
                        return Err("ExecModeSetRequest.reason must be ≤ 500 chars".into());
                    }
                }
            }
        }
        Ok(())
    }
}

/// Persisted inbox row.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentInboxRecord {
    pub id: i64,
    pub recipient_agent_id: String,
    pub recipient_member_id: Option<String>,
    pub sender_agent_id: String,
    pub sender_member_id: Option<String>,
    pub org_run_id: Option<String>,
    pub payload_kind: String,
    pub payload_json: String,
    pub request_id: Option<String>,
    pub created_at: String,
    pub read_at: Option<String>,
}

impl AgentInboxRecord {
    /// Re-hydrate the typed `AgentMessage` from the persisted JSON
    /// payload. Returns a stable error string on schema drift; callers
    /// surface this through whichever transport applies (debug endpoint,
    /// LLM tool-error, drain-loop log).
    pub fn decode_payload(&self) -> Result<AgentMessage, String> {
        serde_json::from_str(&self.payload_json)
            .map_err(|err| format!("decode AgentMessage payload (id={}) failed: {err}", self.id))
    }
}

/// Insertion parameters for the inbox.
#[derive(Debug, Clone)]
pub struct InsertInboxParams {
    pub recipient_agent_id: String,
    pub recipient_member_id: Option<String>,
    pub sender_agent_id: String,
    pub sender_member_id: Option<String>,
    pub org_run_id: Option<String>,
    pub message: AgentMessage,
}

/// Initialize the `agent_inbox` table.
///
/// Hot-path indexes:
/// - `(recipient_member_id, read_at, created_at)` — materialized org member drain query.
/// - `(recipient_agent_id, read_at, created_at)` — coordinator / legacy drain query.
/// - `(org_run_id, created_at)` — debug / E2E "list every message in this
///   run" view.
/// - `(request_id)` — RPC correlation lookups.
pub fn init_schema(conn: &Connection) -> SqliteResult<()> {
    create_agent_inbox_table(conn)?;
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_agent_inbox_recipient_member_unread
            ON agent_inbox(recipient_member_id, read_at, created_at);
        CREATE INDEX IF NOT EXISTS idx_agent_inbox_recipient_unread
            ON agent_inbox(recipient_agent_id, read_at, created_at);
        CREATE INDEX IF NOT EXISTS idx_agent_inbox_org_run
            ON agent_inbox(org_run_id, created_at);
        CREATE INDEX IF NOT EXISTS idx_agent_inbox_request_id
            ON agent_inbox(request_id);",
    )
}

fn create_agent_inbox_table(conn: &Connection) -> SqliteResult<()> {
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS agent_inbox (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            recipient_agent_id TEXT NOT NULL,
            recipient_member_id TEXT,
            sender_agent_id TEXT NOT NULL,
            sender_member_id TEXT,
            org_run_id TEXT,
            payload_kind TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            request_id TEXT,
            created_at TEXT NOT NULL,
            read_at TEXT
        );",
    )
}

pub struct AgentInboxStore;

impl AgentInboxStore {
    /// Persist a message and return the inserted record. The caller is
    /// responsible for resolving display-name / broadcast targets to one or
    /// more concrete `AgentId`s before calling this — the store does not
    /// fan out by itself. The router owns that resolution.
    pub fn insert(params: InsertInboxParams) -> Result<AgentInboxRecord, String> {
        with_sessions_writer(|| -> Result<AgentInboxRecord, String> {
            let conn = get_connection().map_err(|err| err.to_string())?;
            Self::insert_in_tx(&conn, params)
        })
    }

    /// Insert an inbox row using an existing writer transaction.
    ///
    /// This keeps state transitions such as "plan changes requested" and
    /// their durable feedback delivery atomic: a caller cannot commit the
    /// state change while losing the message that explains it.
    pub(crate) fn insert_in_tx(
        conn: &Connection,
        params: InsertInboxParams,
    ) -> Result<AgentInboxRecord, String> {
        params.message.validate()?;

        let kind = params.message.kind_tag().to_string();
        let request_id = params.message.request_id().map(|r| r.0.clone());
        let payload_json = serde_json::to_string(&params.message)
            .map_err(|err| format!("serialize AgentMessage failed: {err}"))?;
        let now = chrono::Utc::now().to_rfc3339();

        conn.execute(
            "INSERT INTO agent_inbox (
                    recipient_agent_id,
                    recipient_member_id,
                    sender_agent_id,
                    sender_member_id,
                    org_run_id,
                    payload_kind,
                    payload_json,
                    request_id,
                    created_at,
                    read_at
                ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, NULL)",
            params![
                &params.recipient_agent_id,
                params.recipient_member_id.as_deref(),
                &params.sender_agent_id,
                params.sender_member_id.as_deref(),
                params.org_run_id.as_deref(),
                &kind,
                &payload_json,
                request_id.as_deref(),
                &now,
            ],
        )
        .map_err(|err| err.to_string())?;
        let id = conn.last_insert_rowid();
        Ok(AgentInboxRecord {
            id,
            recipient_agent_id: params.recipient_agent_id,
            recipient_member_id: params.recipient_member_id,
            sender_agent_id: params.sender_agent_id,
            sender_member_id: params.sender_member_id,
            org_run_id: params.org_run_id,
            payload_kind: kind,
            payload_json,
            request_id,
            created_at: now,
            read_at: None,
        })
    }
}

impl AgentInboxStore {
    /// Return every inbox row for a given Agent Org run, ordered by
    /// insert time. Production callers:
    ///
    /// - `/test/agent-org/inbox/list-by-run` debug endpoint — drives
    ///   the inter-agent E2E observability path.
    pub fn list_by_run(org_run_id: &str) -> Result<Vec<AgentInboxRecord>, String> {
        let conn = get_connection().map_err(|err| err.to_string())?;
        let mut stmt = conn
            .prepare(
                "SELECT id,
                        recipient_agent_id,
                        recipient_member_id,
                        sender_agent_id,
                        sender_member_id,
                        org_run_id,
                        payload_kind,
                        payload_json,
                        request_id,
                        created_at,
                        read_at
                 FROM agent_inbox
                 WHERE org_run_id = ?1
                 ORDER BY id ASC",
            )
            .map_err(|err| err.to_string())?;
        let rows = stmt
            .query_map(params![org_run_id], row_to_record)
            .map_err(|err| err.to_string())?;
        let mut out = Vec::new();
        for row in rows {
            out.push(row.map_err(|err| err.to_string())?);
        }
        Ok(out)
    }
}

fn row_to_record(row: &rusqlite::Row<'_>) -> SqliteResult<AgentInboxRecord> {
    Ok(AgentInboxRecord {
        id: row.get(0)?,
        recipient_agent_id: row.get(1)?,
        recipient_member_id: row.get(2)?,
        sender_agent_id: row.get(3)?,
        sender_member_id: row.get(4)?,
        org_run_id: row.get(5)?,
        payload_kind: row.get(6)?,
        payload_json: row.get(7)?,
        request_id: row.get(8)?,
        created_at: row.get(9)?,
        read_at: row.get(10)?,
    })
}

impl AgentInboxStore {
    /// `EXISTS`-style unread probe. Periodic scanners (watchdog) only
    /// need the boolean; loading and decoding full rows for it is
    /// wasted work.
    pub fn has_unread_for_member(
        recipient_member_id: &str,
        org_run_id: &str,
    ) -> Result<bool, String> {
        let conn = get_connection().map_err(|err| err.to_string())?;
        conn.query_row(
            "SELECT EXISTS(
                 SELECT 1 FROM agent_inbox
                 WHERE recipient_member_id = ?1
                   AND org_run_id = ?2
                   AND read_at IS NULL
             )",
            params![recipient_member_id, org_run_id],
            |row| row.get::<_, bool>(0),
        )
        .map_err(|err| err.to_string())
    }

    pub fn list_unread_for_member(
        recipient_member_id: &str,
        org_run_id: &str,
    ) -> Result<Vec<AgentInboxRecord>, String> {
        let conn = get_connection().map_err(|err| err.to_string())?;
        let mut stmt = conn
            .prepare(
                "SELECT id,
                        recipient_agent_id,
                        recipient_member_id,
                        sender_agent_id,
                        sender_member_id,
                        org_run_id,
                        payload_kind,
                        payload_json,
                        request_id,
                        created_at,
                        read_at
                 FROM agent_inbox
                 WHERE recipient_member_id = ?1
                   AND org_run_id = ?2
                   AND read_at IS NULL
                 ORDER BY id ASC",
            )
            .map_err(|err| err.to_string())?;
        let rows = stmt
            .query_map(params![recipient_member_id, org_run_id], row_to_record)
            .map_err(|err| err.to_string())?;
        let mut out = Vec::new();
        for row in rows {
            out.push(row.map_err(|err| err.to_string())?);
        }
        Ok(out)
    }

    /// Mark a batch of inbox rows as read in a single immediate
    /// transaction. Idempotent: rows that are already read return
    /// `0` updates and do not error. Returns the total number of rows
    /// whose `read_at` was actually advanced.
    ///
    /// Used by the turn-processor drain hook after rendering the
    /// attachment, so the next turn's drain returns an empty list.
    pub fn mark_many_read(ids: &[i64]) -> Result<usize, String> {
        if ids.is_empty() {
            return Ok(0);
        }
        with_sessions_writer(|| -> Result<usize, String> {
            let mut conn = get_connection().map_err(|err| err.to_string())?;
            let tx = conn
                .transaction_with_behavior(rusqlite::TransactionBehavior::Immediate)
                .map_err(|err| err.to_string())?;
            let now = chrono::Utc::now().to_rfc3339();
            let mut updated = 0usize;
            {
                let mut stmt = tx
                    .prepare(
                        "UPDATE agent_inbox SET read_at = ?1 WHERE id = ?2 AND read_at IS NULL",
                    )
                    .map_err(|err| err.to_string())?;
                for id in ids {
                    let n = stmt
                        .execute(params![&now, id])
                        .map_err(|err| err.to_string())?;
                    updated += n;
                }
            }
            tx.commit().map_err(|err| err.to_string())?;
            Ok(updated)
        })
    }
}

// Other read-side store methods (`mark_read` for a single id,
// `find_by_request_id`) will land alongside the next consumer that
// actually needs them. They are intentionally not added here because
// there is no production caller — see `architecture-audit` skill,
// anti-pattern #29 ("Grep-alive = alive — reference counting is not
// a dead code audit").

#[cfg(test)]
mod tests {
    use super::*;

    fn sandbox_with_inbox_schema() -> test_helpers::test_env::SandboxGuard {
        let sandbox = test_helpers::test_env::sandbox();
        let conn = get_connection().expect("open sandbox database");
        init_schema(&conn).expect("initialize agent inbox schema");
        sandbox
    }

    #[test]
    fn plain_validation() {
        let msg = AgentMessage::Plain {
            summary: "ping".into(),
            text: "hello".into(),
        };
        assert!(msg.validate().is_ok());
        assert_eq!(msg.kind_tag(), "plain");
        assert!(msg.request_id().is_none());

        let bad = AgentMessage::Plain {
            summary: "".into(),
            text: "hello".into(),
        };
        assert!(bad.validate().is_err());
    }

    #[test]
    fn rpc_request_id_round_trip() {
        let req_id = RequestId::new();
        let msg = AgentMessage::ShutdownRequest {
            request_id: req_id.clone(),
            reason: Some("done".into()),
        };
        assert_eq!(msg.request_id(), Some(&req_id));
        assert_eq!(msg.kind_tag(), "shutdown_request");
        assert!(msg.validate().is_ok());
    }

    #[test]
    fn plan_approval_request_validates_required_fields() {
        let ok = AgentMessage::PlanApprovalRequest {
            request_id: RequestId("req-1".into()),
            approval_id: "approval-1".into(),
            plan_revision_id: "revision-1".into(),
            source_task_id: "task-plan".into(),
            plan_title: "Refactor auth".into(),
            plan_path: "/tmp/auth.plan.md".into(),
            plan_content: "# steps".into(),
        };
        assert!(ok.validate().is_ok());
        assert_eq!(ok.kind_tag(), "plan_approval_request");
        assert!(ok.is_structured());

        let bad_title = AgentMessage::PlanApprovalRequest {
            request_id: RequestId("req-2".into()),
            approval_id: "approval-2".into(),
            plan_revision_id: "revision-2".into(),
            source_task_id: "task-plan".into(),
            plan_title: "  ".into(),
            plan_path: "/tmp/x".into(),
            plan_content: "body".into(),
        };
        assert!(bad_title.validate().is_err());

        let bad_path = AgentMessage::PlanApprovalRequest {
            request_id: RequestId("req-3".into()),
            approval_id: "approval-3".into(),
            plan_revision_id: "revision-3".into(),
            source_task_id: "task-plan".into(),
            plan_title: "t".into(),
            plan_path: "".into(),
            plan_content: "body".into(),
        };
        assert!(bad_path.validate().is_err());

        let bad_content = AgentMessage::PlanApprovalRequest {
            request_id: RequestId("req-4".into()),
            approval_id: "approval-4".into(),
            plan_revision_id: "revision-4".into(),
            source_task_id: "task-plan".into(),
            plan_title: "t".into(),
            plan_path: "/tmp/x".into(),
            plan_content: "   ".into(),
        };
        assert!(bad_content.validate().is_err());
    }

    #[test]
    fn plan_approval_response_round_trip() {
        let approved = AgentMessage::PlanApprovalResponse {
            request_id: RequestId("req-rt".into()),
            accepted: true,
            feedback: None,
            next_mode: Some(AgentExecMode::Build),
        };
        let json = serde_json::to_string(&approved).unwrap();
        let parsed: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(approved, parsed);
        assert!(json.contains("\"kind\":\"plan_approval_response\""));

        let rejected = AgentMessage::PlanApprovalResponse {
            request_id: RequestId("req-rj".into()),
            accepted: false,
            feedback: Some("scope is wrong".into()),
            next_mode: Some(AgentExecMode::Plan),
        };
        assert!(rejected.validate().is_ok());
    }

    #[test]
    fn is_structured_distinguishes_plain_from_rpc() {
        assert!(!AgentMessage::Plain {
            summary: "s".into(),
            text: "t".into()
        }
        .is_structured());
        assert!(AgentMessage::ShutdownRequest {
            request_id: RequestId::new(),
            reason: None
        }
        .is_structured());
        assert!(AgentMessage::ShutdownResponse {
            request_id: RequestId::new(),
            accepted: true,
            note: None
        }
        .is_structured());
    }

    #[test]
    fn serde_round_trip_via_tag() {
        let msg = AgentMessage::Plain {
            summary: "s".into(),
            text: "t".into(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, parsed);
        assert!(json.contains("\"kind\":\"plain\""));
    }

    #[test]
    fn member_idle_unfinished_tasks_are_backward_compatible_and_omit_empty_wire_data() {
        let message = AgentMessage::MemberIdle {
            member_id: "member-worker".into(),
            member_name: "Worker".into(),
            reason: MemberIdleReason::Available,
            current_mode: Some(AgentExecMode::Build),
            summary: None,
            failure_reason: None,
            unfinished_task_ids: Vec::new(),
        };
        let serialized = serde_json::to_string(&message).expect("serialize MemberIdle");
        assert!(!serialized.contains("unfinished_task_ids"));

        let legacy = r#"{"kind":"member_idle","member_id":"member-worker","member_name":"Worker","reason":"available","current_mode":"build","summary":null,"failure_reason":null}"#;
        let decoded: AgentMessage = serde_json::from_str(legacy).expect("decode legacy MemberIdle");
        assert_eq!(decoded, message);
    }

    #[test]
    fn list_by_run_round_trips_in_insert_order() {
        let _sandbox = sandbox_with_inbox_schema();
        let run_id = format!("run-{}", uuid::Uuid::new_v4());
        let other_run_id = format!("run-{}", uuid::Uuid::new_v4());

        // Two messages on the run we care about, plus one on a sibling run
        // — list_by_run must filter out the sibling.
        let first = AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-1".into(),
            recipient_member_id: Some("member-worker-1".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(run_id.clone()),
            message: AgentMessage::Plain {
                summary: "kickoff".into(),
                text: "begin".into(),
            },
        })
        .expect("insert first");
        let second = AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "coord".into(),
            recipient_member_id: Some("coordinator".into()),
            sender_agent_id: "worker-1".into(),
            sender_member_id: None,
            org_run_id: Some(run_id.clone()),
            message: AgentMessage::ShutdownRequest {
                request_id: RequestId("req-shut-1".into()),
                reason: Some("done".into()),
            },
        })
        .expect("insert second");
        let _ = AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-1".into(),
            recipient_member_id: Some("member-worker-1".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(other_run_id.clone()),
            message: AgentMessage::Plain {
                summary: "other".into(),
                text: "irrelevant".into(),
            },
        })
        .expect("insert other-run row");

        let rows = AgentInboxStore::list_by_run(&run_id).expect("list_by_run");
        assert_eq!(rows.len(), 2, "only the run-scoped rows must surface");
        assert_eq!(rows[0].id, first.id);
        assert_eq!(rows[1].id, second.id);
        assert_eq!(rows[0].payload_kind, "plain");
        assert_eq!(rows[1].payload_kind, "shutdown_request");
        assert_eq!(rows[1].request_id.as_deref(), Some("req-shut-1"));
    }

    #[test]
    fn decode_payload_round_trip() {
        let _sandbox = sandbox_with_inbox_schema();
        let run_id = format!("run-{}", uuid::Uuid::new_v4());
        let original = AgentMessage::ShutdownResponse {
            request_id: RequestId("req-shut-roundtrip".into()),
            accepted: true,
            note: Some("clean exit".into()),
        };
        let record = AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-2".into(),
            recipient_member_id: Some("member-worker-2".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(run_id),
            message: original.clone(),
        })
        .expect("insert");
        let decoded = record.decode_payload().expect("decode");
        assert_eq!(decoded, original);
    }

    /// Regression guard: every variant's `kind_tag()` MUST equal the
    /// serde `tag = "kind"` string. The `payload_kind` SQLite column
    /// is populated from `kind_tag()` and queried via the JSON tag, so a
    /// drift here silently corrupts the inbox.
    #[test]
    fn kind_tag_matches_serde_tag() {
        let cases: Vec<AgentMessage> = vec![
            AgentMessage::Plain {
                summary: "s".into(),
                text: "t".into(),
            },
            AgentMessage::ShutdownRequest {
                request_id: RequestId::new(),
                reason: None,
            },
            AgentMessage::ShutdownResponse {
                request_id: RequestId::new(),
                accepted: true,
                note: None,
            },
            AgentMessage::PlanApprovalRequest {
                request_id: RequestId::new(),
                approval_id: "approval-1".into(),
                plan_revision_id: "revision-1".into(),
                source_task_id: "task-plan".into(),
                plan_title: "title".into(),
                plan_path: "/tmp/x.plan.md".into(),
                plan_content: "body".into(),
            },
            AgentMessage::PlanApprovalResponse {
                request_id: RequestId::new(),
                accepted: true,
                feedback: None,
                next_mode: Some(AgentExecMode::Build),
            },
            AgentMessage::MemberTerminated {
                member_id: "alice".into(),
                member_name: "alice".into(),
                reason: MemberTerminationReason::Shutdown,
            },
            AgentMessage::MemberIdle {
                member_id: "alice".into(),
                member_name: "alice".into(),
                reason: MemberIdleReason::Available,
                current_mode: Some(AgentExecMode::Plan),
                summary: Some("DM'd coord with progress".into()),
                failure_reason: None,
                unfinished_task_ids: Vec::new(),
            },
            AgentMessage::TaskAssigned {
                task_id: "task-1".into(),
                subject: "subject".into(),
                description: "d".into(),
                assigned_by: "Coord".into(),
                dependency_outputs: Vec::new(),
                execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Build,
            },
            AgentMessage::TaskCompleted {
                task_id: "task-1".into(),
                subject: "subject".into(),
                completed_by_member_id: "alice".into(),
                output_summary: Some("done".into()),
                remaining_open_task_count: 0,
            },
            AgentMessage::ExecModeSetRequest {
                request_id: RequestId::new(),
                mode: AgentExecMode::Plan,
                reason: Some("draft a plan first".into()),
            },
        ];
        for msg in cases {
            let json = serde_json::to_value(&msg).unwrap();
            let serde_tag = json
                .get("kind")
                .and_then(|v| v.as_str())
                .unwrap_or_else(|| panic!("missing kind on {}", msg.kind_tag()));
            assert_eq!(
                serde_tag,
                msg.kind_tag(),
                "kind_tag() drift for {:?}",
                msg.kind_tag()
            );
        }
    }

    /// `MemberTerminated` is the system-emitted notification the
    /// coordinator-side drain produces after cancelling a member that
    /// acknowledged shutdown. Pin: kind tag, structured-ness (broadcast
    /// guard depends on it), validate() rejects empty agent_id/name, and
    /// the wire format includes `reason` as a snake_case string.
    #[test]
    fn member_terminated_validate_serde_and_kind_tag() {
        let ok = AgentMessage::MemberTerminated {
            member_id: "alice".into(),
            member_name: "alice".into(),
            reason: MemberTerminationReason::Shutdown,
        };
        assert!(ok.validate().is_ok());
        assert_eq!(ok.kind_tag(), "member_terminated");
        assert!(
            ok.is_structured(),
            "MemberTerminated must be structured so the broadcast guard rejects fan-out"
        );
        assert!(
            ok.request_id().is_none(),
            "MemberTerminated has no RPC correlation"
        );

        let json = serde_json::to_value(&ok).unwrap();
        assert_eq!(json["kind"], "member_terminated");
        assert_eq!(json["member_id"], "alice");
        assert_eq!(json["member_name"], "alice");
        assert_eq!(json["reason"], "shutdown");

        let parsed: AgentMessage = serde_json::from_value(json).unwrap();
        assert_eq!(parsed, ok);

        let bad_id = AgentMessage::MemberTerminated {
            member_id: "  ".into(),
            member_name: "alice".into(),
            reason: MemberTerminationReason::Shutdown,
        };
        assert!(bad_id.validate().is_err());

        let bad_name = AgentMessage::MemberTerminated {
            member_id: "alice".into(),
            member_name: "".into(),
            reason: MemberTerminationReason::Shutdown,
        };
        assert!(bad_name.validate().is_err());
    }

    #[test]
    fn list_unread_filters_by_recipient_run_and_unread() {
        let _sandbox = sandbox_with_inbox_schema();
        let run_id = format!("run-{}", uuid::Uuid::new_v4());
        let other_run = format!("run-{}", uuid::Uuid::new_v4());

        let in_scope = AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-1".into(),
            recipient_member_id: Some("member-worker-1".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(run_id.clone()),
            message: AgentMessage::Plain {
                summary: "in".into(),
                text: "yes".into(),
            },
        })
        .expect("in-scope");

        // Wrong recipient — must be excluded.
        AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-2".into(),
            recipient_member_id: Some("member-worker-2".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(run_id.clone()),
            message: AgentMessage::Plain {
                summary: "wrong-recipient".into(),
                text: "no".into(),
            },
        })
        .expect("wrong-recipient");

        // Wrong run — must be excluded.
        AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-1".into(),
            recipient_member_id: Some("member-worker-1".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(other_run),
            message: AgentMessage::Plain {
                summary: "wrong-run".into(),
                text: "no".into(),
            },
        })
        .expect("wrong-run");

        // Same delivery agent id but different member id — must be excluded
        // from member-id drain.
        AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-1".into(),
            recipient_member_id: Some("member-other-worker".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(run_id.clone()),
            message: AgentMessage::Plain {
                summary: "member-scoped".into(),
                text: "no".into(),
            },
        })
        .expect("member-scoped");

        let unread = AgentInboxStore::list_unread_for_member("member-worker-1", &run_id)
            .expect("list_unread");
        assert_eq!(unread.len(), 1);
        assert_eq!(unread[0].id, in_scope.id);
        assert!(unread[0].read_at.is_none());
    }

    #[test]
    fn mark_many_read_is_idempotent_and_advances_watermark() {
        let _sandbox = sandbox_with_inbox_schema();
        let run_id = format!("run-{}", uuid::Uuid::new_v4());
        let one = AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-1".into(),
            recipient_member_id: Some("member-worker-1".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(run_id.clone()),
            message: AgentMessage::Plain {
                summary: "a".into(),
                text: "1".into(),
            },
        })
        .expect("one");
        let two = AgentInboxStore::insert(InsertInboxParams {
            recipient_agent_id: "worker-1".into(),
            recipient_member_id: Some("member-worker-1".into()),
            sender_agent_id: "coord".into(),
            sender_member_id: None,
            org_run_id: Some(run_id.clone()),
            message: AgentMessage::Plain {
                summary: "b".into(),
                text: "2".into(),
            },
        })
        .expect("two");

        let updated = AgentInboxStore::mark_many_read(&[one.id, two.id]).expect("first mark");
        assert_eq!(updated, 2);

        // Second call is a no-op (idempotent) — already-read rows
        // contribute zero to the count.
        let again = AgentInboxStore::mark_many_read(&[one.id, two.id]).expect("second mark");
        assert_eq!(again, 0);

        let still_unread = AgentInboxStore::list_unread_for_member("member-worker-1", &run_id)
            .expect("list_unread");
        assert!(
            still_unread.is_empty(),
            "marked rows must vanish from the unread list"
        );
    }

    #[test]
    fn mark_many_read_empty_input_is_ok() {
        let _sandbox = sandbox_with_inbox_schema();
        let updated = AgentInboxStore::mark_many_read(&[]).expect("empty");
        assert_eq!(updated, 0);
    }

    #[test]
    fn task_assigned_validation_and_metadata() {
        let ok = AgentMessage::TaskAssigned {
            task_id: "task-1".into(),
            subject: "Refactor auth".into(),
            description: "Move bcrypt cost to env".into(),
            assigned_by: "Coordinator".into(),
            dependency_outputs: Vec::new(),
            execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Build,
        };
        assert!(ok.validate().is_ok());
        assert_eq!(ok.kind_tag(), "task_assigned");
        assert!(ok.is_structured());
        assert!(ok.request_id().is_none());
    }

    #[test]
    fn task_assigned_rejects_blank_required_fields() {
        let bad_id = AgentMessage::TaskAssigned {
            task_id: "  ".into(),
            subject: "s".into(),
            description: "d".into(),
            assigned_by: "by".into(),
            dependency_outputs: Vec::new(),
            execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Build,
        };
        assert!(bad_id.validate().is_err());

        let bad_subject = AgentMessage::TaskAssigned {
            task_id: "task-1".into(),
            subject: "".into(),
            description: "d".into(),
            assigned_by: "by".into(),
            dependency_outputs: Vec::new(),
            execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Build,
        };
        assert!(bad_subject.validate().is_err());

        let bad_assigned_by = AgentMessage::TaskAssigned {
            task_id: "task-1".into(),
            subject: "s".into(),
            description: "d".into(),
            assigned_by: "".into(),
            dependency_outputs: Vec::new(),
            execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Build,
        };
        assert!(bad_assigned_by.validate().is_err());
    }

    #[test]
    fn task_assigned_rejects_oversized_payload() {
        let bad_subject = AgentMessage::TaskAssigned {
            task_id: "task-1".into(),
            subject: "x".repeat(201),
            description: "d".into(),
            assigned_by: "by".into(),
            dependency_outputs: Vec::new(),
            execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Build,
        };
        assert!(bad_subject.validate().is_err());

        let bad_description = AgentMessage::TaskAssigned {
            task_id: "task-1".into(),
            subject: "s".into(),
            description: "x".repeat(4001),
            assigned_by: "by".into(),
            dependency_outputs: Vec::new(),
            execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Build,
        };
        assert!(bad_description.validate().is_err());
    }

    #[test]
    fn task_assigned_round_trips_through_serde() {
        let msg = AgentMessage::TaskAssigned {
            task_id: "task-42".into(),
            subject: "Pagination on /search".into(),
            description: "Add cursor-based paging".into(),
            assigned_by: "Alice".into(),
            dependency_outputs: Vec::new(),
            execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode::Plan,
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, parsed);
        // Tag must be the wire-stable snake_case discriminator.
        assert!(json.contains("\"kind\":\"task_assigned\""));
    }

    #[test]
    fn task_completed_round_trips_and_validates() {
        let msg = AgentMessage::TaskCompleted {
            task_id: "task-42".into(),
            subject: "Review draft".into(),
            completed_by_member_id: "reviewer".into(),
            output_summary: Some("Approved with two corrections".into()),
            remaining_open_task_count: 0,
        };
        assert!(msg.validate().is_ok());
        assert_eq!(msg.kind_tag(), "task_completed");
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, parsed);
    }

    /// `ExecModeSetRequest` is the coordinator's mode-flip channel.
    /// Pin: kind tag, structured-ness, request_id required, mode is a
    /// snake_case wire string, reason length cap.
    #[test]
    fn exec_mode_set_request_validate_serde_and_kind_tag() {
        let ok = AgentMessage::ExecModeSetRequest {
            request_id: RequestId("req-mode-1".into()),
            mode: AgentExecMode::Plan,
            reason: Some("draft a plan first".into()),
        };
        assert!(ok.validate().is_ok());
        assert_eq!(ok.kind_tag(), "exec_mode_set_request");
        assert!(ok.is_structured());
        assert_eq!(ok.request_id().map(|r| r.as_str()), Some("req-mode-1"));

        let json = serde_json::to_value(&ok).unwrap();
        assert_eq!(json["kind"], "exec_mode_set_request");
        assert_eq!(json["mode"], "plan");

        let bad_request = AgentMessage::ExecModeSetRequest {
            request_id: RequestId("   ".into()),
            mode: AgentExecMode::Build,
            reason: None,
        };
        assert!(bad_request.validate().is_err());

        let bad_reason = AgentMessage::ExecModeSetRequest {
            request_id: RequestId("req".into()),
            mode: AgentExecMode::Build,
            reason: Some("x".repeat(501)),
        };
        assert!(bad_reason.validate().is_err());
    }

    #[test]
    fn exec_mode_set_request_round_trips_through_serde() {
        let msg = AgentMessage::ExecModeSetRequest {
            request_id: RequestId("req-mode-rt".into()),
            mode: AgentExecMode::Ask,
            reason: None,
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, parsed);
        assert!(json.contains("\"kind\":\"exec_mode_set_request\""));
        assert!(json.contains("\"mode\":\"ask\""));
    }
}
